# Generated by Django 3.0.7 on 2020-07-01 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetEntryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='budgetmonthly',
            name='day_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='budgetmonthly',
            name='month_number',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='budgetmonthly',
            name='year_number',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='budgetmonthly',
            name='category_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='budget.BudgetEntryCategory'),
            preserve_default=False,
        ),
    ]
