# Generated by Django 3.0.7 on 2020-07-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20200701_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetmonthly',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
